import jobsRouter from '@modules/jobs/jobs.routes';
import userRouter from '@modules/user/user.routes';
import appliedCandidatesRouter from '@modules/applied-candidates/applied-candidates.routes';
import automationsRouter from '@modules/automations/automations.route';
import { Router } from 'express';
import employeeAutomationRouter from '@modules/employee_automation/employee_automation.route';
import locationRouter from '@modules/location/location.route';
import messagesRouter from '@modules/messages/messages.routes';
import employerRouter from '@modules/employer/employer.route';
import talentScoutRouter from '@modules/talent-scout/talent-scout.route';
import dashboardRouter from '@modules/dashboard/dashboard.routes';
import jobSeekerdashboardRouter from '@modules/job-seeker-dashboard/job-seeker-dashboard.routes';
import createJobAlertsforJobSeekersRouter from '@modules/job-alerts/job-alerts.routes';
const router = Router();

router.use('/users', userRouter);
router.use('/jobs', jobsRouter);
router.use('/applied-candidates',appliedCandidatesRouter);
router.use('/automations',automationsRouter);
router.use('/employee-automation', employeeAutomationRouter);
router.use('/locations',locationRouter);
router.use('/employer', employerRouter);
router.use('/messages', messagesRouter); 
router.use('/talent-scout',talentScoutRouter);
router.use('/dashboard',dashboardRouter);
router.use('/job-seeker-dashboard',jobSeekerdashboardRouter);
router.use('/job-alerts-for-jobseekers',createJobAlertsforJobSeekersRouter);
export default router;
